### ISSUE TITLE
No hover effect on buttons

### ISSUE THREAD

**Issue by mosch** [allthings/elements#136]
We don't have any hover / active state on our buttons. I think it's time to fix that.

Maybe @monsterlie @fivenp any ideas on that? I would love to have something fun that more than just a simple "change color". Maybe something more unicornish? 🦄

**Comment by fivenp** [comment]
For the hover I guess we can't go thaaaat crazy - but even something like [here](https://tympanus.net/Development/CreativeButtons/) (blue background - 2nd col - 2nd button) would look cool

Regarding the active state we could get a little bit more fancy (e.g. last button on the linked page) - but we need to keep in mind that since we're optimistic the active state of a button is only visible for ~10ms or so 

Shall we also define a color-rule for buttons? Something like hover effects use the passed in background color and get darkened() by 15%? Actvice state reverts to the original background color and darkens it by only 5%?

We would also need a contrast check to determine whether the button is still readable with the supplied colors (otherwise we could invert the text-color)

**Comment by mosch** [comment]
I love the first one, however i think it's too much to be the default 🎆 
Maybe a restrained version of the [second one](https://dribbble.com/shots/3634421-Fancy-Button)?

**Comment by fivenp** [comment]
I can kinda see [this](https://dribbble.com/shots/3634421-Fancy-Button) with a 15% (or whatever darker color) to transparent radial gradient background working quite nicely. 

On click/active we could simply "fill" the whole button with that background color instead of having the gradient....

**Comment by monsterlie** [comment]
![unicorn_button](https://user-images.githubusercontent.com/30181026/36590859-592e4a50-1890-11e8-9c21-a2b0b36375e3.gif)

**Comment by fivenp** [comment]
@monsterlie when written words turn to visuals... <3

**Comment by fivenp** [comment]
so we would have something like [this](https://codepen.io/anon/pen/YejYLE) for free standing buttons

and something like [this](https://codepen.io/anon/pen/YejYmL) for floating-buttons or full-size buttons which have bordered parents (card-buttons, etc) 

right?

**Comment by monsterlie** [comment]
jep that looks good :)

**Comment by mosch** [comment]
fixed in #583
